name: build binary for all platforms

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
  build-linux:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build
      - run: mv jingle jingle-linux
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: jingle-linux
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
  build-mac:
    runs-on: darwin-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build
      - run: mv jingle jingle-macos
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: jingle-macos
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
  build-windows:
    runs-on: windows-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: go build
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: jingle.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
